# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20161117_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField()),
                ('money', models.DecimalField(decimal_places=4, max_digits=14)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Broker')),
            ],
        ),
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField()),
                ('project', models.CharField(choices=[('IPO', 'IPO'), ('Long', 'Long'), ('Short', 'Short')], max_length=10)),
                ('money', models.DecimalField(decimal_places=4, max_digits=14)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Broker')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockCode')),
            ],
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='code',
        ),
        migrations.RemoveField(
            model_name='dividend',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='moneyin',
            name='stock',
        ),
        migrations.DeleteModel(
            name='StockIn',
        ),
        migrations.AddField(
            model_name='stockadd',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.StockMaster'),
        ),
        migrations.AddField(
            model_name='dividend',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.StockMaster'),
        ),
        migrations.AddField(
            model_name='moneyin',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.StockMaster'),
        ),
    ]
