# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockmaster_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividend',
            name='quantity',
        ),
    ]
