# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_dividend_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField()),
                ('money', models.DecimalField(decimal_places=4, max_digits=14)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, 'Buy'), (2, 'Sell'), (3, 'Dividend'), (4, 'TranOut'), (5, 'TranIn')])),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Broker')),
            ],
        ),
        migrations.RemoveField(
            model_name='dividend',
            name='master',
        ),
        migrations.RemoveField(
            model_name='moneyin',
            name='master',
        ),
        migrations.RemoveField(
            model_name='stockadd',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='stockadd',
            name='master',
        ),
        migrations.RemoveField(
            model_name='stockmaster',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='stockmaster',
            name='money',
        ),
        migrations.RemoveField(
            model_name='stockmaster',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stockmaster',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Dividend',
        ),
        migrations.DeleteModel(
            name='MoneyIn',
        ),
        migrations.DeleteModel(
            name='StockAdd',
        ),
        migrations.AddField(
            model_name='transaction',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.StockMaster'),
        ),
    ]
