# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20161122_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmaster',
            options={'ordering': ['-add_date']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-add_date']},
        ),
        migrations.AddField(
            model_name='stockcode',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='stockcode',
            name='latest_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
